In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB

In [4]:
df=pd.read_csv('agaricus-lepiota.csv')
df

      p  x  s  n  t p.1  f  c n.1  k  ... s.2  w w.1 p.2 w.2  o p.3 k.1 s.3  u
0     e  x  s  y  t   a  f  c   b  k  ...   s  w   w   p   w  o   p   n   n  g
1     e  b  s  w  t   l  f  c   b  n  ...   s  w   w   p   w  o   p   n   n  m
2     p  x  y  w  t   p  f  c   n  n  ...   s  w   w   p   w  o   p   k   s  u
3     e  x  s  g  f   n  f  w   b  k  ...   s  w   w   p   w  o   e   n   a  g
4     e  x  y  y  t   a  f  c   b  n  ...   s  w   w   p   w  o   p   k   n  g
...  .. .. .. .. ..  .. .. ..  .. ..  ...  .. ..  ..  ..  .. ..  ..  ..  .. ..
8118  e  k  s  n  f   n  a  c   b  y  ...   s  o   o   p   o  o   p   b   c  l
8119  e  x  s  n  f   n  a  c   b  y  ...   s  o   o   p   n  o   p   b   v  l
8120  e  f  s  n  f   n  a  c   b  n  ...   s  o   o   p   o  o   p   b   c  l
8121  p  k  y  n  f   y  f  c   n  b  ...   k  w   w   p   w  o   e   w   v  l
8122  e  x  s  n  f   n  a  c   b  y  ...   s  o   o   p   o  o   p   o   c  l

[8123 rows x 23 columns]

In [5]:
df.isnull().sum()

p      0
x      0
s      0
n      0
t      0
p.1    0
f      0
c      0
n.1    0
k      0
e      0
e.1    0
s.1    0
s.2    0
w      0
w.1    0
p.2    0
w.2    0
o      0
p.3    0
k.1    0
s.3    0
u      0
dtype: int64

In [6]:
df.shape

(8123, 23)

In [7]:
df.dtypes

p      object
x      object
s      object
n      object
t      object
p.1    object
f      object
c      object
n.1    object
k      object
e      object
e.1    object
s.1    object
s.2    object
w      object
w.1    object
p.2    object
w.2    object
o      object
p.3    object
k.1    object
s.3    object
u      object
dtype: object

In [8]:
#Observation: All the attributes are in object datatype. So convert it into integer type by using Label Encoder.

In [9]:
from sklearn.preprocessing import LabelEncoder

In [10]:
from sklearn import preprocessing

In [11]:
le=preprocessing.LabelEncoder()

In [12]:
df=df.apply(le.fit_transform)

In [13]:
df

,p,x,s,n,t,p.1,f,c,n.1,k,...,s.2,w,w.1,p.2,w.2,o,p.3,k.1,s.3,u
0,0,5,2,9,1,0,1,0,0,4,...,2,7,7,0,2,1,4,3,2,1
1,0,0,2,8,1,3,1,0,0,5,...,2,7,7,0,2,1,4,3,2,3
2,1,5,3,8,1,6,1,0,1,5,...,2,7,7,0,2,1,4,2,3,5
3,0,5,2,3,0,5,1,1,0,4,...,2,7,7,0,2,1,0,3,0,1
4,0,5,3,9,1,0,1,0,0,5,...,2,7,7,0,2,1,4,2,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8118,0,3,2,4,0,5,0,0,0,11,...,2,5,5,0,1,1,4,0,1,2
8119,0,5,2,4,0,5,0,0,0,11,...,2,5,5,0,0,1,4,0,4,2
8120,0,2,2,4,0,5,0,0,0,5,...,2,5,5,0,1,1,4,0,1,2
8121,1,3,3,4,0,8,1,0,1,0,...,1,7,7,0,2,1,0,7,4,2
8122,0,5,2,4,0,5,0,0,0,11,...,2,5,5,0,1,1,4,4,1,2

In [14]:
y=df.iloc[:,0]
y

0       0
1       0
2       1
3       0
4       0
       ..
8118    0
8119    0
8120    0
8121    1
8122    0
Name: p, Length: 8123, dtype: int32

In [15]:
x=df.iloc[:,1:23]
x

,x,s,n,t,p.1,f,c,n.1,k,e,...,s.2,w,w.1,p.2,w.2,o,p.3,k.1,s.3,u
0,5,2,9,1,0,1,0,0,4,0,...,2,7,7,0,2,1,4,3,2,1
1,0,2,8,1,3,1,0,0,5,0,...,2,7,7,0,2,1,4,3,2,3
2,5,3,8,1,6,1,0,1,5,0,...,2,7,7,0,2,1,4,2,3,5
3,5,2,3,0,5,1,1,0,4,1,...,2,7,7,0,2,1,0,3,0,1
4,5,3,9,1,0,1,0,0,5,0,...,2,7,7,0,2,1,4,2,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8118,3,2,4,0,5,0,0,0,11,0,...,2,5,5,0,1,1,4,0,1,2
8119,5,2,4,0,5,0,0,0,11,0,...,2,5,5,0,0,1,4,0,4,2
8120,2,2,4,0,5,0,0,0,5,0,...,2,5,5,0,1,1,4,0,1,2
8121,3,3,4,0,8,1,0,1,0,1,...,1,7,7,0,2,1,0,7,4,2
8122,5,2,4,0,5,0,0,0,11,0,...,2,5,5,0,1,1,4,4,1,2

In [16]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.22,random_state=42)

In [17]:
lr=LogisticRegression()

In [18]:
lr.fit(x_train,y_train)
lr.score(x_train,y_train)

C:\Users\Suncity\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)

0.9505919494869771

In [19]:
predlr = lr.predict(x_test)
print(accuracy_score(y_test,predlr))
print(confusion_matrix(y_test,predlr))
print(classification_report(y_test,predlr))

0.9513422818791947
[[903  40]
 [ 47 798]]
              precision    recall  f1-score   support

           0       0.95      0.96      0.95       943
           1       0.95      0.94      0.95       845

    accuracy                           0.95      1788
   macro avg       0.95      0.95      0.95      1788
weighted avg       0.95      0.95      0.95      1788

In [20]:
gnb=GaussianNB()
gnb.fit(x_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [21]:
predgb=lr.predict(x_test)
print(accuracy_score(y_test,predgb))
print(confusion_matrix(y_test,predgb))
print(classification_report(y_test,predgb))

0.9513422818791947
[[903  40]
 [ 47 798]]
              precision    recall  f1-score   support

           0       0.95      0.96      0.95       943
           1       0.95      0.94      0.95       845

    accuracy                           0.95      1788
   macro avg       0.95      0.95      0.95      1788
weighted avg       0.95      0.95      0.95      1788

In [22]:
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
import warnings
warnings.filterwarnings ('ignore')

In [23]:
svc=SVC(kernel='rbf')
svc.fit(x_train,y_train)
predsvc=svc.predict(x_test)
print(accuracy_score(y_test,predsvc))
print(confusion_matrix(y_test,predsvc))
print(classification_report(y_test,predsvc))

0.9876957494407159
[[942   1]
 [ 21 824]]
              precision    recall  f1-score   support

           0       0.98      1.00      0.99       943
           1       1.00      0.98      0.99       845

    accuracy                           0.99      1788
   macro avg       0.99      0.99      0.99      1788
weighted avg       0.99      0.99      0.99      1788

In [24]:
dtc1=DecisionTreeClassifier()
dtc1.fit(x_train,y_train)
dtc1.score(x_train,y_train)
preddtc=dtc1.predict(x_test)
print(accuracy_score(y_test,preddtc))
print(confusion_matrix(y_test,preddtc))
print(classification_report(y_test,preddtc))

1.0
[[943   0]
 [  0 845]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       943
           1       1.00      1.00      1.00       845

    accuracy                           1.00      1788
   macro avg       1.00      1.00      1.00      1788
weighted avg       1.00      1.00      1.00      1788

In [25]:
from sklearn.neighbors import KNeighborsClassifier
dtc2=KNeighborsClassifier()
dtc2.fit(x_train,y_train)
dtc2.score(x_train,y_train)
preddtc=dtc2.predict(x_test)
print(accuracy_score(y_test,preddtc))
print(confusion_matrix(y_test,preddtc))
print(classification_report(y_test,preddtc))

1.0
[[943   0]
 [  0 845]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       943
           1       1.00      1.00      1.00       845

    accuracy                           1.00      1788
   macro avg       1.00      1.00      1.00      1788
weighted avg       1.00      1.00      1.00      1788

In [26]:
def svmkernel(ker):
    svc=SVC(kernel=ker)
    svc.fit(x_train,y_train)
    predsvc=svc.predict(x_test)
    print(accuracy_score(y_test,predsvc))
    print(confusion_matrix(y_test,predsvc))
    print(classification_report(y_test,predsvc))

In [27]:
svmkernel('poly')

0.9994407158836689
[[943   0]
 [  1 844]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       943
           1       1.00      1.00      1.00       845

    accuracy                           1.00      1788
   macro avg       1.00      1.00      1.00      1788
weighted avg       1.00      1.00      1.00      1788

In [28]:
svmkernel('rbf')

0.9876957494407159
[[942   1]
 [ 21 824]]
              precision    recall  f1-score   support

           0       0.98      1.00      0.99       943
           1       1.00      0.98      0.99       845

    accuracy                           0.99      1788
   macro avg       0.99      0.99      0.99      1788
weighted avg       0.99      0.99      0.99      1788

In [29]:
svmkernel('linear')

0.9580536912751678
[[905  38]
 [ 37 808]]
              precision    recall  f1-score   support

           0       0.96      0.96      0.96       943
           1       0.96      0.96      0.96       845

    accuracy                           0.96      1788
   macro avg       0.96      0.96      0.96      1788
weighted avg       0.96      0.96      0.96      1788

In [30]:
#cross validation of model
from sklearn.model_selection import cross_val_score

In [31]:
dtc1=DecisionTreeClassifier()
score=cross_val_score(dtc1,x,y,cv=5)
print(score)
print(score.mean())
print(score.std())

[0.88246154 1.         1.         1.         0.68965517]
0.9144233421750663
0.12125376705728523

In [32]:
dtc2=KNeighborsClassifier()
score=cross_val_score(dtc2,x,y,cv=5)
print(score)
print(score.mean())
print(score.std())

[0.84430769 0.99753846 0.93046154 1.         0.63362069]
0.8811856763925731
0.1361846783280626

In [33]:
#saving the model
from sklearn.externals import joblib
joblib.dump(dtc1,'mushroom.pkl')

['mushroom.pkl']